[package]
name = "rust_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
cty = "0.2.2"
rnarduino = { path = "../../lnArduino/rust/rnArduino"}
ufmt = "*"

[lib]
name = "rust_demo"
path = "src/lib.rs"
crate-type = ["staticlib"] # Creates static lib

[profile.dev]
debug = true
lto = false
opt-level       = 0

[profile.release]
debug = true
lto = true
opt-level       = 0
